# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#library(RcppGSL)
BayesRB <- function(seed, MCMC_inte, burn_intee, thinn, X, Y, beta_initial) {
  .Call('BayesRB_BayesRB', PACKAGE = 'BayesRB',seed, MCMC_inte, burn_intee, thinn, X, Y, beta_initial)
}

